baseurl = "http://liaoqinchao.github.io/"
title = "Hacking lifet"
languageCode = "en-us"
disqusShortname = "LQC"
copyright = "Copyright (c) 2014 - 2015, Liaoqinchao; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "Qinchao Liao"

[indexes]
    tag = "tags"
    topic = "topics"
[params]  
  themeColor = "theme-base-0c"
  description = "做一个享受生活的程序猿"
